services:
  db:
    image: pgvector/pgvector:pg16
    container_name: inboxai-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inboxai
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d inboxai && psql -U postgres -d inboxai -c 'SELECT 1'",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  migrations:
    image: migrate/migrate:latest
    container_name: inboxai-migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://postgres:postgres@db:5432/inboxai?sslmode=disable",
        "up",
      ]
    volumes:
      - ./db/migrations:/migrations
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

  api:
    build: ./apps/api
    container_name: inboxai-api
    env_file: ./.env.local
    depends_on:
      migrations:
        condition: service_completed_successfully
      ollama:
        condition: service_started
    ports:
      - "3001:3001"

  ollama:
    image: ollama/ollama:latest
    container_name: inboxai-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    entrypoint: [
        "/bin/sh",
        "-lc",
        "ollama serve & \
        sleep 2 && \
        ollama pull mistral:7b-instruct && \
        ollama pull nomic-embed-text || true && \
        wait",
      ]

volumes:
  db:
  ollama:
